version: "3.2"

services:
  #MariaDB Container
  mariadb:
    image: mariadb:10.7
    container_name: mariadb
    hostname: mariadb
    volumes:
      - ./configs/mysql/database:/var/lib/mysql
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - rede

  #GLPI Container
  glpi:
    image: diouxx/glpi
    container_name: glpi
    hostname: glpi
    ports:
      - "8075:80"
    volumes:
      # - ./glpi/:/var/www/html/glpi
      - ./glpi/:/var/www/html/glpi-homolog
      # - ./configs/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - TIMEZONE=America/Fortaleza
      - VERSION_GLPI=9.5.7
    restart: unless-stopped
    networks:
      - rede

networks:
  rede:
    driver: bridge
