version: "3.2"

services:
#MariaDB Container
  mariadb:
    image: mariadb:10.7
    container_name: mariadb
    hostname: mariadb
    volumes:
      - ./configs/mysql/database:/var/lib/mysql
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - rede

#GLPI Container
  glpi:
    image: diouxx/glpi
    container_name : glpi
    hostname: glpi
    ports:
      - "8075:80"
    volumes:
      # - /configs/etc/timezone:/etc/timezone:ro
      # - /configs/etc/localtime:/etc/localtime:ro
      - ./glpi/:/var/www/html/glpi
      # - ./theme/dted.scss:/var/www/html/glpi/css/palettes/dted.scss
    environment:
      - TIMEZONE=America/Fortaleza
    restart: unless-stopped
    networks:
      - rede

networks:
  rede:
    driver: bridge